### ISSUE TITLE
Failed to verify broker certificate: unable to get local issuer certificate

### ISSUE THREAD

**Issue by harjul** [CloudKarafka/python-kafka-example#3] opened 2018-05-30 12:29 UTC
Hello Experts,

Where should I place the certificate? I followed the installation guidelines but didn't find where to put the certificate. Please guide as I am getting error while running  python consumer.py command.

Regards

**Comment by RafaMunoz** [comment] 2018-06-08 21:10
Hello,

I receive the same error.
Did you find any solution?

Regards

**Comment by jashwanth** [comment] 2018-06-10 01:35
I have tried to resolve this issue by adding the below line to the config dictionary
'ssl.ca.location': '<Absolute-Path-Certificate-File>'. However the callback is triggered that message was sent to a partiton of a topic, but i see no messages on the clusters in www.cloudkarafka.com  and its metrics aren't updated as well. Any help in this regard will be appreciated..

**Comment by RafaMunoz** [comment] 2018-06-10 11:27
Finally I found my problem. I lacked to install **librdkafka**.

Once installed the library, the producer published messages but the consumer did not receive them. I had to change the value of setting **'group.id'** to group1 and it started to work.

I hope it helps you.

**Comment by jashwanth** [comment] 2018-06-10 17:40
Thank You very much. It worked for me as well. Could I please know why changing the group.id to group1 works?

**Comment by RafaMunoz** [comment] 2018-06-10 17:46
I'm not sure but with the setting **'group.id': "cloudkarafka-example"** on the consumer.py it did not work for me. 
It was changed to **'group.id': "group1"** and started to get messages. 

Possibly **"-"** would be giving some conflict, but I tried with other values ​​in group.id and if that works.

**Comment by snichme** [comment] 2018-06-11 06:27
Hi, 

The reason that it doesn't work with a group id like cloudkarafka-example is that our free plan "Developer Duck" host all on the same shared kafka cluster. And ownership of a group id belongs to the user first using it. Which means that if someone connects using another account but the same group id that user will have no permissions to use that group id and thus, no messages will arrive even if consuming from correct topic. 

I've updated the code to prefix the consumer group with the username, using this approach there will be no permissions issues and no conflicts in naming consumer groups. 

So please update your code to prefix the consumer group with your username.

Note: this only applies to the free plan, all other plans are on dedicated servers and doesn't have this limitation.

**Comment by vishalsaroha** [comment] 2018-08-18 11:29
This is an old post and saw the similar error which people have faced earlier. I am facing the same error.

"Failed to verify broker certificate: unable to get local issuer certificate"
I have created my free node on cloudfarafka.com and using all the right values for brokers,username n all. My topic name is "username-default" as suggested in previous posts.
As per the sample producers and consumers given in the code section, there is no configuration required. If we still need to use the certificate from cloudkarafka which is given under cert column, can you please guide as how to use it.

Or any other suggestion as how I can make this code work.

**Comment by juank11memphis** [comment] 2018-09-25 17:08
Hi, 

I am also getting the `Failed to verify broker certificate: unable to get local issuer certificate` error.

Can someone please help me on how to fix this, I am using python but inside a Docker container.
I am not sure what do I need to do to make this work inside Docker.

Any help would be highly appreciated.

Thanks

**Comment by henadzit** [comment] 2018-10-02 15:53
Hi @snichme, 

I'm having the same issue trying to connect to cloudkarafka from a slim-based docker instance. I tried to install `librdkafka1` from confluent's repo but it didn't help. It's very unfortunate because we're evaluating Cloudkarafka as our Kafka provider.

Thanks,
Henadzi

**Comment by snichme** [comment] 2018-10-02 17:24
Hi @juank11memphis and @henadzit 

Could you send me the Dockerfile and I will have a go to see if I can find the issue. 

You can post them here or send them to support@cloudkarafka.com (it's me receiving those emails) if you don't want to share here. 
I will post the solution here for all once resolved.

**Comment by henadzit** [comment] 2018-10-02 18:00
Hey @snichme, thanks for the quick reply. I set up a small repo with Dockerfile showing the issue - https://github.com/henadzit/cloudkarafka-test-project.

**Comment by snichme** [comment] 2018-10-03 11:27
The reason for this message is that librdkafka cannot find the Root CA certificate on the host to verify our servers.  For librdkafka you can choose to let it find the cert on the host or you can specify a ca cert for it to use. 
Most docker images seems to be missing the root ca cert, so you can either install it on the image or you can specify it in the config to librdkafka
Look here for an example: https://github.com/snichme/cloudkarafka-test-project/commit/3e6f2e9d4eeffb2977e80327cc89251d242dda8c
We use the same ca cert for all brokers so using the link in the docker file should work for everyone and the config option is the same for all language as long as the client uses librdkafka.

**Comment by henadzit** [comment] 2018-10-03 11:34
Confirm that the solution provided @snichme solved the issue. Thank you for resolving this!

**Comment by sapka12** [comment] 2019-02-02 23:17
hi @snichme 

I have the same issue. I'm trying to produce messages to CloudKarafka (Developer Duck Plan) with python3.6 and i have 'Failed to verify broker certificate: unable to get local issuer certificate' error.

I've downloaded the .ca file and added 

> 'ssl.ca.location': './cloudkarafka.ca'

 to my config but got the same error (the .ca was placed well: I got another error if I changed the path of it).

i've also cloned and tried @henadzit 's [repo](https://github.com/henadzit/cloudkarafka-test-project) but I got the same error in Docker as well.

can you please help me. what else shall I set up? why did not work the docker version? Is @henadzit 's repo still valid, can you produce with it?

**Comment by carlosevi94** [comment] 2019-02-15 09:16
I'm on the same situation of @sapka12 
I try the same. 
In my case fail too.

**Comment by carlosevi94** [comment] 2019-02-19 08:42
Is posible reopen this issue?  Isn't working yet.
Isn't working for me and I reproduce the docker file in AWS and some computers.

I don't know if to @sapka12 works or not.

Edit:
Following the @snichme  solution, that improve a Docker, I follow exactly the same commands in bash and I get this:

```bash
%3|1550566443.490|FAIL|rdkafka#producer-1| [thrd:ark-03.srvs.cloudkafka.com:9094/bootstrap]: ark-03.srvs.cloudkafka.com:9094/bootstrap: Disconnected (after 801ms in state UP)
%3|1550566443.490|ERROR|rdkafka#producer-1| [thrd:ark-03.srvs.cloudkafka.com:9094/bootstrap]: ark-03.srvs.cloudkafka.com:9094/bootstrap: Disconnected (after 801ms in state UP)
%3|1550566443.530|FAIL|rdkafka#producer-1| [thrd:ark-02.srvs.cloudkafka.com:9094/bootstrap]: ark-02.srvs.cloudkafka.com:9094/bootstrap: Disconnected (after 250ms in state UP)
%3|1550566443.530|ERROR|rdkafka#producer-1| [thrd:ark-02.srvs.cloudkafka.com:9094/bootstrap]: ark-02.srvs.cloudkafka.com:9094/bootstrap: Disconnected (after 250ms in state UP)
%3|1550566443.569|FAIL|rdkafka#producer-1| [thrd:ark-03.srvs.cloudkafka.com:9094/bootstrap]: ark-03.srvs.cloudkafka.com:9094/bootstrap: Disconnected (after 40ms in state UP)
%3|1550566443.569|ERROR|rdkafka#producer-1| [thrd:ark-03.srvs.cloudkafka.com:9094/bootstrap]: ark-03.srvs.cloudkafka.com:9094/bootstrap: Disconnected (after 40ms in state UP)
%3|1550566443.607|FAIL|rdkafka#producer-1| [thrd:ark-01.srvs.cloudkafka.com:9094/bootstrap]: ark-01.srvs.cloudkafka.com:9094/bootstrap: Disconnected (after 288ms in state UP)
%3|1550566443.607|ERROR|rdkafka#producer-1| [thrd:ark-01.srvs.cloudkafka.com:9094/bootstrap]: ark-01.srvs.cloudkafka.com:9094/bootstrap: Disconnected (after 288ms in state UP)
%3|1550566443.607|ERROR|rdkafka#producer-1| [thrd:ark-01.srvs.cloudkafka.com:9094/bootstrap]: 3/3 brokers are down
```

**Comment by carlosevi94** [comment] 2019-03-07 12:37
Still does not work

**Comment by slackcc** [comment] 2019-03-13 01:57
I am also getting this error when attempting to connect using the python example code. I've tried both on a Mac and an EC2 instance and get the same results. I've tried downloading the certs from my cloudkarafka.com instance using:

`openssl s_client -showcerts -servername server -connect velomobile-01.srvs.cloudkafka.com:9094 > ck.pem`

And then loading that .pem file into ssl.ca.location in the conf section, is this the right way to obtain the certificate needed for the CA? The odd thing is that I tried this a few months ago and I believe everything worked fine but now it doesn't seem to be working.

If anyone has any suggestions I would be quite happy to hear them.

Thanks,

Chris

**Comment by snichme** [comment] 2019-03-18 13:33
During January all shared servers got new certificates because the older one was about to expire, when we change the server certificate we also updated the CA certificate that should be used. 
We have updated our FAQ with a more in-depth answer to this issue, please have a look here: https://www.cloudkarafka.com/docs/faq.html#connect--failed-to-verify

@carlosevi94 If you are using the docker image that has been referenced in this issue, make you that you rebuild the image, the new certificate only gets downloaded on build and not when you run the image. 

@slackcc you should not have to export the cert from the response of the openssl command, you can download from https://www.cloudkarafka.com/docs/faq.html

**Comment by sapka12** [comment] 2019-03-24 19:14
@snichme thanks the fix, it works for me now.

**Comment by dentarg** [comment] 2020-11-11 13:09
A heads-up for those who are still trusting our SSL certificate explicitly. In mid-december, our certificate will be updated once again, and the certificate chain will change.

Please see our blog for details: https://www.cloudkarafka.com/blog/2020-11-10-ssl-certificate-renewal.html

**Closed as completed** 2020-12-30 15:45 UTC
